config/routes.rb
Rails.application.routes.draw do
  resources :references
  resources :periodics
  get 'pages/info'
  get 'home/index'
  root "home#index"
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/my_logger.rb
module MyLogger
  def log(message, message_color: :green)
    puts '~'.yellow.bold * 100
    puts "DateTime: #{DateTime.now}"
    puts '~'.yellow.bold * 100
    puts message.try(message_color)
    puts '~'.yellow.bold * 100
  end

  module_function :log
end

app/models/periodic.rb
class Periodic < ApplicationRecord
  require 'csv'
  require 'activerecord-import/base'
  require 'activerecord-import/active_record/adapters/postgresql_adapter'
  require 'pry'

  belongs_to :user, optional: true

  validates_presence_of :name, :issn, :knowledgement_area, :qualis

  def self.copy_db_from_excel(path)
  end

  def self.convert_to_utf8_encoding(original_file)  
    original_string = original_file.read
    final_string = original_string.encode(invalid: :replace, undef: :replace, replace: '')
    final_file = Tempfile.new('import')
    final_file.write(final_string)
    final_file.close
    final_file
  end

  def self.import! 
    the_file = convert_to_utf8_encoding(File.open('db/periodics_capes_2016.csv'))
    CSV.foreach(Rails.root.join(the_file), col_sep: ';', headers: true) do |row|
      Periodic.create! row.to_hash.slice('issn', 'name', 'knowledgement_area', 'qualis')
      print '.'.green
    end
  end
end

# https://cbabhusal.wordpress.com/2017/02/09/rails-import-csv-data-to-database/ import csv to postgresql from ruby

app/models/reference.rb
class Reference < ApplicationRecord
  belongs_to :user

  validates_presence_of :title, :authors, :description, :publication_date, :registered_date
end

app/models/user.rb
class User < ApplicationRecord
  has_many :periodics, dependent: :destroy
  has_many :references, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def info
  end
end

app/controllers/periodics_controller.rb
class PeriodicsController < ApplicationController
  before_action :set_periodic, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, :except => [:show, :index]

  # GET /periodics
  # GET /periodics.json
  def index
    @all_knowledgement_areas = Periodic.distinct.pluck(:knowledgement_area).compact.each(&:strip!)
    @all_qualis = Periodic.distinct.pluck(:qualis).compact.each(&:strip!)
    @periodics_count = Periodic.all.count

    if params[:selected_knowledgement_area] && params[:selected_qualis]
      @listage_title = 'Listagem de periódicos pesquisados'
      @periodics = find_periodic(params[:selected_knowledgement_area], params[:selected_qualis]).paginate(page: params[:page], per_page: 80).order('created_at ASC')
      @returned_results_txt = "Total de Periódicos retornados na consulta: #{@periodics.size}"
    else
      @listage_title = 'Listagem de todos os periódicos'
      @returned_results_txt = "Você ainda não realizou uma filtragem na busca"
      @periodics = Periodic.paginate(page: params[:page], per_page: 39).order('created_at ASC')
      respond_to do |format|
        format.html
        format.js
      end
    end
  end

  def find_periodic(knowledgement_area, qualis)
    str = ''
    str_kn = ''

    qualis.each { |q| str += "'#{q.to_s}', "}
    str = str.delete_suffix!(', ')

    knowledgement_area.each { |k| str_kn += "'#{k.to_s}', "}
    str_kn = str_kn.delete_suffix!(', ')
    @found = Periodic.where("qualis IN (#{str}) AND knowledgement_area IN (#{str_kn})")
    @found
  end

  # GET /periodics/1
  # GET /periodics/1.json
  def show
  end

  # GET /periodics/new
  def new
    @periodic = Periodic.new
  end

  # GET /periodics/1/edit
  def edit
  end

  # POST /periodics
  # POST /periodics.json
  def create
    @periodic = Periodic.new(periodic_params)
    @periodic.user = current_user

    respond_to do |format|
      if @periodic.save
        format.html { redirect_to @periodic, notice: 'Periódico registrado com sucesso.' }
        format.json { render :show, status: :created, location: @periodic }
      else
        format.html { render :new }
        format.json { render json: @periodic.errors, status: :unprocessable_entity }
      end
    end
  end

  def create!
    @periodic = Periodic.new(periodic_params)

    respond_to do |format|
      if @periodic.save
        format.html { redirect_to @periodic, notice: 'Periódico registrado com sucesso.' }
        format.json { render :show, status: :created, location: @periodic }
      else
        format.html { render :new }
        format.json { render json: @periodic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /periodics/1
  # PATCH/PUT /periodics/1.json
  def update
    respond_to do |format|
      if @periodic.update(periodic_params)
        format.html { redirect_to @periodic, notice: 'Periódico atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @periodic }
      else
        format.html { render :edit }
        format.json { render json: @periodic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /periodics/1
  # DELETE /periodics/1.json
  def destroy
    @periodic.destroy
    respond_to do |format|
      format.html { redirect_to periodics_url, notice: 'Periódico excluido com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_periodic
      @periodic = Periodic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def periodic_params
      params.require(:periodic).permit(:name, :description, :qualis, :knowledgement_area, :issn, :selected_knowledgement_area, :selected_qualis)
    end
end

app/controllers/references_controller.rb
class ReferencesController < ApplicationController
  before_action :set_reference, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, :except => [:show, :index]

  # GET /references
  # GET /references.json
  def index
    @references = Reference.all
  end

  # GET /references/1
  # GET /references/1.json
  def show
  end

  # GET /references/new
  def new
    @reference = Reference.new
  end

  # GET /references/1/edit
  def edit
  end

  # POST /references
  # POST /references.json
  def create
    @reference = Reference.new(reference_params)
    @reference.user = current_user
    @reference.registered_date = Date.today()

    respond_to do |format|
      if @reference.save
        format.html { redirect_to @reference, notice: 'Referência criada com sucesso.' }
        format.json { render :show, status: :created, location: @reference }
      else
        format.html { render :new }
        format.json { render json: @reference.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /references/1
  # PATCH/PUT /references/1.json
  def update
    respond_to do |format|
      if @reference.update(reference_params)
        format.html { redirect_to @reference, notice: 'Referência atualizada com sucesso.' }
        format.json { render :show, status: :ok, location: @reference }
      else
        format.html { render :edit }
        format.json { render json: @reference.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /references/1
  # DELETE /references/1.json
  def destroy
    @reference.destroy
    respond_to do |format|
      format.html { redirect_to references_url, notice: 'Referência removida.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reference
      @reference = Reference.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reference_params
      params.require(:reference).permit(:title, :authors, :description, :publication_date, :registered_date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/periodics_helper.rb
module PeriodicsHelper
end

app/helpers/references_helper.rb
module ReferencesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Study Boost</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap-theme.css"> -->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <a class="navbar-brand" href="/">Study Boost</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active"> <a class="nav-link" href="/periodics">Pesquisar por periódicos</a> </li>
        <% if user_signed_in? %>
          <li class="nav-item active"> <a class="nav-link" href="/references">Cadastrar referência bibliográfica</a> </li>
        <% end %>
        <li class="nav-item active"> <a class="nav-link" href="/pages/info">Sobre</a> </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          Logado como: <strong><%= current_user.email %></strong>.
          <li class="nav-item active">
            <%= link_to 'Editar perfil', edit_user_registration_path, :class => 'nav-link' %>
          </li>
          <li class="nav-item active">
            <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'nav-link' %>
          </li>
        <% else %>
          <li class="nav-item active">
            <%= link_to "Registrar-se", new_user_registration_path, :class => 'nav-link' %>
          </li>
          <li class="nav-item active"> 
            <%= link_to "Login", new_user_session_path, :class => 'nav-link' %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>

<!--    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Study Boost</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a href="/periodics">Pesquisar por periódicos</a></li>
            <% if user_signed_in? %>
              <li><a href="/references">Cadastrar referência bibliográfica</a></li>
            <% end %>
            <li><a href="/pages/info">Sobre</a></li>
            <li> <p class="navbar-text pull-right">
              <% if user_signed_in? %>
                Logado como: <strong><%= current_user.email %></strong>.
                <%= link_to 'Editar perfil', edit_user_registration_path, :class => 'navbar-link' %> |
                <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
              <% else %>
                <%= link_to "Registrar-se", new_user_registration_path, :class => 'navbar-link'  %> |
                <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
              <% end %>
          </p></li>
          </ul>
        </div>
      </div>
    </nav> -->

    <div class="container">
      <%= yield %>
    </div>

    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <footer class="fixed-bottom footer">
      <div class="container">
        <span class="text-muted">Study Boost, <%= Time.now.year %>.</span>
      </div>
    </footer>
    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.js"></script> -->
  </body>
</html>

app/views/pages/info.html.erb
<h1>Sobre o projeto</h1>
<p style="font-size: 18px;">Projeto criado com o intuíto de facilitar a busca por periódicos para publicações, relacionando áreas do conhecimento e qualis, além de facilitar o arquivamento de 
referências bibliográficas. </p>

<p style="font-size: 18px;">Projeto em desenvolvimento incremental, existem melhorias sendo implementadas, e também novas funcionalidades sendo adicionadas periodicamente.</p>


<hr>
<h2 style="text-align: center;"> Perguntas Frequentes </h2>
<div class="container py-3">
    <div class="row">
        <div class="col-10 mx-auto">
            <div class="accordion" id="faqExample">
                <div class="card">
                    <div class="card-header p-2" id="headingOne">
                        <h5 class="mb-0">
                            <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                              Pergunta: Qual a finalidade do projeto?
                            </button>
                          </h5>
                    </div>

                    <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#faqExample">
                        <div class="card-body">
                            <b>Resposta:</b> A principal ideia do projeto é a de disponibilizar de forma intuitiva e de fácil acesso um banco de dados com os periódicos cadastrados na CAPES inicialmente, de forma a aumentar esta base em um futuro próximo, e possibilitando a busca por periódicos relacionando áreas e sub-áreas de conhecimento com Qualis, tornando mais fácil a busca por periódicos para publicações.
                        </div>
                    </div>
                </div>
                <div class="card">
                    <div class="card-header p-2" id="headingTwo">
                        <h5 class="mb-0">
                        <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                          Pergunta: Sobre a metodologia de desenvolvimento?
                        </button>
                      </h5>
                    </div>
                    <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#faqExample">
                        <div class="card-body">
                            <b>Resposta:</b> O projeto foi desenvolvido como Trabalho de Conclusão de Curso no curso de Especialização em Aplicações Web pela Universidade Federal do Rio Grande, foi utilizada a metodologia BDD (Behavior Driven Development) para o planejamento e descrição das funcionalidades, e foram implementados testes nos diversos níveis da aplicação.
                        </div>
                    </div>
                </div>
                <div class="card">
                    <div class="card-header p-2" id="headingThree">
                        <h5 class="mb-0">
                            <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                              Pergunta: Projetos similares?
                            </button>
                          </h5>
                    </div>
                    <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#faqExample">
                        <div class="card-body">
                            <b>Resposta:</b> O próprio site do Periódicos Capes possibilita a busca por periódicos, porém não possibilita o relacionamento de áreas de conhecimento com Qualis. Além da principal funcionalidade da aplicação, novas funcionalidades com o intuíto em auxiliar a vida acadêmica irão ser adicionadas regularmente.
                        </div>
                    </div>
                </div>
                <div class="card">
                    <div class="card-header p-2" id="headingThree">
                        <h5 class="mb-0">
                            <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                              Pergunta: Existe uma intenção de expansão de funcionalidades e integrações futuras?
                            </button>
                          </h5>
                    </div>
                    <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#faqExample">
                        <div class="card-body">
                            <b>Resposta:</b> Sim, as principais funcionalidades já implementadas foram a busca por periódicos relacionando áreas de conhecimento e Qualis, e o cadastro de referências bibliográficas para usuários cadastrados, porém novas funcionalidades com o intuito de auxiliar em organização e auxílio acadêmico serão adicionadas.
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
    <!--/row-->
</div>
<!--container-->

app/views/periodics/_form.html.erb
<%= form_with(model: periodic, local: true) do |form| %>
  <% if periodic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(periodic.errors.count, "error") %> Erro ao salvar o periódico:</h2>

      <ul>
      <% periodic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :qualis %>
    <%= form.text_field :qualis %>
  </div>

  <div class="field">
    <%= form.label :knowledgement_area %>
    <%= form.text_field :knowledgement_area %>
  </div>

  <div class="field">
    <%= form.label :issn %>
    <%= form.text_field :issn %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/periodics/edit.html.erb
<h1>Editando Periódico</h1>

<%= render 'form', periodic: @periodic %>

<%= link_to 'Mostrar', @periodic %> |
<%= link_to 'Voltar', periodics_path %>

app/views/periodics/index.html.erb
<p id="notice"><%= notice %></p>

<h2 style="color: #33cc33;"><b> Para filtrar, utilize o formulário abaixo: </b></h2>

<%= form_tag('/periodics', method: :get) do %>
  
  <h5 style="color: #33cc33;"><%= label_tag "Selecione a área de conhecimento"%></h5>
  <div class="form-group">
    <%= select_tag(:selected_knowledgement_area, options_for_select(@all_knowledgement_areas), :multiple=>true, :required=>true, class: 'form-control', placeholder: "batata") %>
  </div>


  <h5 style="color: #33cc33;"><%= label_tag "Selecione todos qualis a serem incluídos na consulta"%></h5>
  <div class="form-group">
    <%= select_tag(:selected_qualis, options_for_select(@all_qualis), :multiple=>true, :required=>true, class: 'form-control') %>
  </div>

  <%= submit_tag 'Filtrar', class: 'btn btn-success btn-block' %>
<% end %>

<hr>

<h4 style="color: #6600ff;"><b> Periódicos retornados: </b></h2>
<!-- <% if user_signed_in? %>
  <%= link_to 'Novo Periódico', new_periodic_path, class: "btn btn-primary btn-md"%>
<% end %> -->

<div id="periodicsTab">

  <table class="table">
    <thead>
      <tr>
        <th scope="col">Nome</th>
        <th scope="col">Qualis</th>
        <th scope="col">Área de conhecimento</th>
        <th scope="col">ISSN</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @periodics.each do |periodic| %>
        <tr>
          <td><%= periodic.name %></td>
          <td><%= periodic.qualis %></td>
          <td><%= periodic.knowledgement_area %></td>
          <td><%= periodic.issn %></td>
          <% if user_signed_in? && !periodic.user.nil? %>
            <% if periodic.user.id == current_user.id %>
              <td><%= link_to 'Mostrar', periodic %></td>
              <td><%= link_to 'Editar', edit_periodic_path(periodic) %></td>
              <td><%= link_to 'Excluir', periodic, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<hr>
<h2 style="color: #6600ff;"><b><%= @listage_title %></b></h2>

<div class="row">
  <div class="col">
    <h5 style="color: #6600ff;"><b>Total de Periódicos cadastrados: <%= @periodics_count  %> </b></h5>
  </div>
  <div class="col">
    <h5 style="color: #6600ff;"><b> <%= @returned_results_txt %> </b></h5>
  </div>
</div>


<hr>

<br>

<div id="infinite-scrolling">
  <%= will_paginate %>
</div>

app/views/periodics/new.html.erb
<h1>Novo Periódico</h1>

<%= render 'form', periodic: @periodic %>

<%= link_to 'Voltar', periodics_path %>

app/views/periodics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @periodic.name %>
</p>

<p>
  <strong>Descrição:</strong>
  <%= @periodic.description %>
</p>

<p>
  <strong>Qualis:</strong>
  <%= @periodic.qualis %>
</p>

<p>
  <strong>Área de conhecimento:</strong>
  <%= @periodic.knowledgement_area %>
</p>

<p>
  <strong>ISSN:</strong>
  <%= @periodic.issn %>
</p>

<%= link_to 'Editar', edit_periodic_path(@periodic) %> |
<%= link_to 'Voltar', periodics_path %>

app/views/references/_form.html.erb
<%= form_with(model: reference, local: true) do |form| %>
  <% if reference.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reference.errors.count, "error") %> impediu que o registro fosse salvo:</h2>

      <ul>
      <% reference.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :title, class: 'sr-only' %>
    <%= form.text_field :title, class: 'form-control', placeholder: 'Título do trabalho' %>
  </div>

  <div class="field form-group">
    <%= form.label :authors, class: 'sr-only' %>
    <%= form.text_field :authors, class: 'form-control', placeholder: 'Autores' %>
  </div>

  <div class="field form-group">
    <%= form.label :description, class: 'sr-only' %>
    <%= form.text_area :description, class: 'form-control', placeholder: 'Descrição do trabalho' %>
  </div>

  <div class="field form-group">
    <%= form.label :publication_date %>
    <%= form.date_select :publication_date, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit "Submeter", class: 'btn btn-lg btn-primary btn-block' %>
  </div>
<% end %>

app/views/references/edit.html.erb
<h1>Editando Referência</h1>

<%= render 'form', reference: @reference %>

<%= link_to 'Mostrar', @reference, class: 'btn btn-primary btn-lg btn-block' %>
<%= link_to 'Voltar', references_path, class: 'btn btn-warning btn-lg btn-block' %>

app/views/references/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Suas Referências</h1>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Título</th>
      <th scope="col">Autores</th>
      <th scope="col">Descrição</th>
      <th scope="col">Data de publicação</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @references.each do |reference| %>
      <tr>
        <td><%= reference.title %></td>
        <td><%= reference.authors %></td>
        <td><%= reference.description %></td>
        <td><%= reference.publication_date %></td>
        <td><%= link_to 'Mostrar', reference, class: 'btn btn-primary btn-lg btn-block' %></td>
        <td><%= link_to 'Editar', edit_reference_path(reference), class: 'btn btn-primary btn-lg btn-block' %></td>
        <td><%= link_to 'Excluir', reference, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-lg btn-block' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nova referência', new_reference_path, class: 'btn btn-primary btn-lg btn-block' %>

app/views/references/new.html.erb
<h1>Nova Referência</h1>

<%= render 'form', reference: @reference %>

<%= link_to 'Voltar', references_path, class: 'btn btn-warning btn-lg btn-block' %>

app/views/references/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Título:</strong>
  <%= @reference.title %>
</p>

<p>
  <strong>Autores:</strong>
  <%= @reference.authors %>
</p>

<p>
  <strong>Descrição:</strong>
  <%= @reference.description %>
</p>

<p>
  <strong>Data de publicação:</strong>
  <%= @reference.publication_date %>
</p>

<%= link_to 'Editar', edit_reference_path(@reference), class: 'btn btn-primary btn-lg btn-block' %>
<%= link_to 'Voltar', references_path, class: 'btn btn-warning btn-lg btn-block' %>